config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :buyers

      resources :sellers

      resources :messages

      resources :users

      resources :categories

      resources :items
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "items#index"
  resources :buyers
  resources :sellers
  resources :messages
  resources :users
  resources :categories
  resources :items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  # Direct associations

  belongs_to :buyer

  belongs_to :seller

  belongs_to :item

  # Indirect associations

  has_one    :user,
             through: :item,
             source: :user

  # Validations

  # Scopes

  def to_s
    seller.to_s
  end
end

app/controllers/api/v1/messages_controller.rb
class Api::V1::MessagesController < Api::V1::GraphitiController
  def index
    messages = MessageResource.all(params)
    respond_with(messages)
  end

  def show
    message = MessageResource.find(params)
    respond_with(message)
  end

  def create
    message = MessageResource.build(params)

    if message.save
      render jsonapi: message, status: :created
    else
      render jsonapi_errors: message
    end
  end

  def update
    message = MessageResource.find(params)

    if message.update_attributes
      render jsonapi: message
    else
      render jsonapi_errors: message
    end
  end

  def destroy
    message = MessageResource.find(params)

    if message.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: message
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[show edit update destroy]

  def index
    @q = Message.ransack(params[:q])
    @messages = @q.result(distinct: true).includes(:item, :seller, :buyer,
                                                   :user).page(params[:page]).per(10)
  end

  def show; end

  def new
    @message = Message.new
  end

  def edit; end

  def create
    @message = Message.new(message_params)

    if @message.save
      message = "Message was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @message, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @message.update(message_params)
      redirect_to @message, notice: "Message was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @message.destroy
    message = "Message was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to messages_url, notice: message
    end
  end

  private

  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:seller_id, :buyer_id, :item_id)
  end
end

app/views/messages/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Message #<%= message.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Seller</dt>
      <dd>
        <% if @message.seller.present? %>
          <%= link_to message.seller, message.seller %>
        <% end %>
      </dd>

      <dt>Buyer</dt>
      <dd>
        <% if @message.buyer.present? %>
          <%= link_to message.buyer, message.buyer %>
        <% end %>
      </dd>

      <dt>Item</dt>
      <dd>
        <% if @message.item.present? %>
          <%= link_to message.item, message.item %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back message, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_message_url(message), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to message, method: :delete, data: { confirm: "Do you really want to delete this message?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(message.updated_at) %> ago
  </div>
</div>

app/views/messages/_form.html.erb
<% was_validated = message.errors.any? %>

<%= form_with(model: message, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% seller_class = "form-control" %>
    <% seller_was_invalid = message.errors.include?(:seller) %>

    <% if was_validated %>
      <% if seller_was_invalid %>
        <% seller_class << " is-invalid" %>
      <% else %>
        <% seller_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :seller_id %>
    <%= f.collection_select :seller_id, Seller.all, :id, :to_s, {}, class: "form-control" %>
    <% if seller_was_invalid %>
      <% message.errors.full_messages_for(:seller).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% buyer_class = "form-control" %>
    <% buyer_was_invalid = message.errors.include?(:buyer) %>

    <% if was_validated %>
      <% if buyer_was_invalid %>
        <% buyer_class << " is-invalid" %>
      <% else %>
        <% buyer_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :buyer_id %>
    <%= f.collection_select :buyer_id, Buyer.all, :id, :to_s, {}, class: "form-control" %>
    <% if buyer_was_invalid %>
      <% message.errors.full_messages_for(:buyer).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% item_class = "form-control" %>
    <% item_was_invalid = message.errors.include?(:item) %>

    <% if was_validated %>
      <% if item_was_invalid %>
        <% item_class << " is-invalid" %>
      <% else %>
        <% item_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :item_id %>
    <%= f.collection_select :item_id, Item.all, :id, :to_s, {}, class: "form-control" %>
    <% if item_was_invalid %>
      <% message.errors.full_messages_for(:item).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/messages/_list_item.html.erb
<%= link_to message, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= message %>
    <small class="text-muted">
      <%= time_ago_in_words(message.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/messages/_messages_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "messages_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :item_title_cont, "Item title contains" %>
    <%= f.text_field :item_title_cont, :class => "form-control", :placeholder => "Item title contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Seller Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='sellergteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :seller_created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Seller Created at greater than or equal to", :data => {:target => '#sellergteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#sellergteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='sellerlteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :seller_created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Seller Created at less than or equal to", :data => {:target => '#sellerlteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#sellerlteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#sellergteqcreated_atPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#sellerlteqcreated_atPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#sellergteqcreated_atPicker').on("dp.change", function (e) {
              $('#sellerlteqcreated_atPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#sellerlteqcreated_atPicker').on("dp.change", function (e) {
              $('#sellergteqcreated_atPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :created_at, "Buyer Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='buyergteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :buyer_created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Buyer Created at greater than or equal to", :data => {:target => '#buyergteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#buyergteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='buyerlteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :buyer_created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Buyer Created at less than or equal to", :data => {:target => '#buyerlteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#buyerlteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#buyergteqcreated_atPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#buyerlteqcreated_atPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#buyergteqcreated_atPicker').on("dp.change", function (e) {
              $('#buyerlteqcreated_atPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#buyerlteqcreated_atPicker').on("dp.change", function (e) {
              $('#buyergteqcreated_atPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :user_email_cont, "User email contains" %>
    <%= f.text_field :user_email_cont, :class => "form-control", :placeholder => "User email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/messages" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#messages_filters">
  Show filters
</a>

app/views/messages/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Message #<%= @message.id %>
      </h2>

      <div class="card-body">
        <%= render "form", message: @message %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/messages/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Messages

      <%= link_to new_message_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "messages/messages_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Messages

        <%= link_to new_message_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @messages, partial: "list_item", as: :message %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @messages, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/messages/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Message
      </h2>

      <div class="card-body">
        <%= render "form", message: @message %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/messages/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @message, partial: "card", as: :message %>
  </div>
</div>