config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :buyers

      resources :sellers

      resources :messages

      resources :users

      resources :categories

      resources :items
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "items#index"
  resources :buyers
  resources :sellers
  resources :messages
  resources :users
  resources :categories
  resources :items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  # Direct associations

  has_many   :messages,
             dependent: :destroy

  has_many   :items,
             dependent: :destroy

  has_many   :users,
             dependent: :destroy

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    created_at
  end
end

app/controllers/api/v1/buyers_controller.rb
class Api::V1::BuyersController < Api::V1::GraphitiController
  def index
    buyers = BuyerResource.all(params)
    respond_with(buyers)
  end

  def show
    buyer = BuyerResource.find(params)
    respond_with(buyer)
  end

  def create
    buyer = BuyerResource.build(params)

    if buyer.save
      render jsonapi: buyer, status: :created
    else
      render jsonapi_errors: buyer
    end
  end

  def update
    buyer = BuyerResource.find(params)

    if buyer.update_attributes
      render jsonapi: buyer
    else
      render jsonapi_errors: buyer
    end
  end

  def destroy
    buyer = BuyerResource.find(params)

    if buyer.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: buyer
    end
  end
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: %i[show edit update destroy]

  def index
    @q = Buyer.ransack(params[:q])
    @buyers = @q.result(distinct: true).includes(:users, :items,
                                                 :messages).page(params[:page]).per(10)
  end

  def show
    @message = Message.new
    @item = Item.new
    @user = User.new
  end

  def new
    @buyer = Buyer.new
  end

  def edit; end

  def create
    @buyer = Buyer.new(buyer_params)

    if @buyer.save
      redirect_to @buyer, notice: "Buyer was successfully created."
    else
      render :new
    end
  end

  def update
    if @buyer.update(buyer_params)
      redirect_to @buyer, notice: "Buyer was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @buyer.destroy
    redirect_to buyers_url, notice: "Buyer was successfully destroyed."
  end

  private

  def set_buyer
    @buyer = Buyer.find(params[:id])
  end

  def buyer_params
    params.fetch(:buyer, {})
  end
end

app/views/buyers/_buyer_items.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Items

    <a data-toggle="collapse" href="#buyer_items_new_form">
      Add item
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @buyer.items.each do |item| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to item, item %>

        <%= link_to item, method: :delete, data: { confirm: "Do you really want to delete this item" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="buyer_items_new_form">
        <%= render partial: "buyers/buyer_items_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/buyers/_buyer_items_new_form.html.erb
<%= form_with(model: @item, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :title %>

    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>

    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>

    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category_id %>

    <%= f.collection_select :category_id, Category.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :location %>

    <%= f.text_field :location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>

    <%= f.text_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :seller_id %>

    <%= f.collection_select :seller_id, Seller.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :buyer_id, value: @buyer.id %>

  <%= f.submit "Create item", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/buyers/_buyer_messages.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Messages

    <a data-toggle="collapse" href="#buyer_messages_new_form">
      Add message
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @buyer.messages.each do |message| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to message, message %>

        <%= link_to message, method: :delete, data: { confirm: "Do you really want to delete this message" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="buyer_messages_new_form">
        <%= render partial: "buyers/buyer_messages_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/buyers/_buyer_messages_new_form.html.erb
<%= form_with(model: @message, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :seller_id %>

    <%= f.collection_select :seller_id, Seller.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :buyer_id, value: @buyer.id %>

  <div class="form-group">
    <%= f.label :item_id %>

    <%= f.collection_select :item_id, Item.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Create message", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/buyers/_buyer_users.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Users

    <a data-toggle="collapse" href="#buyer_users_new_form">
      Add user
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @buyer.users.each do |user| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to user, user %>

        <%= link_to user, method: :delete, data: { confirm: "Do you really want to delete this user" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="buyer_users_new_form">
        <%= render partial: "buyers/buyer_users_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/buyers/_buyer_users_new_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :email %>

    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>

    <%= f.text_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :seller_id %>

    <%= f.collection_select :seller_id, Seller.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :buyer_id, value: @buyer.id %>

  <div class="form-group">
    <%= f.label :name %>

    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.submit "Create user", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/buyers/_buyers_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "buyers_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :users_email_cont, "Users email contains" %>
    <%= f.text_field :users_email_cont, :class => "form-control", :placeholder => "Users email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :items_title_cont, "Items title contains" %>
    <%= f.text_field :items_title_cont, :class => "form-control", :placeholder => "Items title contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/buyers" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#buyers_filters">
  Show filters
</a>

app/views/buyers/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Buyer #<%= buyer.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back buyer, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_buyer_url(buyer), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to buyer, method: :delete, data: { confirm: "Do you really want to delete this buyer?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(buyer.updated_at) %> ago
  </div>
</div>

app/views/buyers/_form.html.erb
<% was_validated = buyer.errors.any? %>

<%= form_with(model: buyer, local: true, novalidate: true, class: "mb-3") do |f| %>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/buyers/_list_item.html.erb
<%= link_to buyer, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= buyer %>
    <small class="text-muted">
      <%= time_ago_in_words(buyer.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/buyers/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Buyer #<%= @buyer.id %>
      </h2>

      <div class="card-body">
        <%= render "form", buyer: @buyer %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/buyers/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Buyers

      <%= link_to new_buyer_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "buyers/buyers_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Buyers

        <%= link_to new_buyer_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @buyers, partial: "list_item", as: :buyer %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @buyers, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/buyers/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Buyer
      </h2>

      <div class="card-body">
        <%= render "form", buyer: @buyer %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/buyers/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @buyer, partial: "card", as: :buyer %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "buyers/buyer_users" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "buyers/buyer_items" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "buyers/buyer_messages" %>
  </div>
</div>